# Generated by Django 4.1.7 on 2023-02-26 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название песни')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist_app.artist', verbose_name='Артист')),
            ],
            options={
                'verbose_name': 'Песня',
                'verbose_name_plural': 'Песни',
                'unique_together': {('title', 'artist')},
            },
        ),
    ]
