# Generated by Django 4.1.7 on 2023-02-26 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('song_app', '0001_initial'),
        ('artist_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название альбома')),
                ('year_release', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist_app.artist', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
        migrations.CreateModel(
            name='AlbumSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='Позиция в альбоме')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album_app.album', verbose_name='Исполнитель')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song_app.song', verbose_name='Песня')),
            ],
            options={
                'unique_together': {('song', 'position')},
            },
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(through='album_app.AlbumSong', to='song_app.song'),
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('name', 'artist')},
        ),
    ]
